### ISSUE TITLE
Open source of the code

### ISSUE THREAD

**Issue by zhiwenfan** [tejaskhot/unsup_mvs#2]
Thank you for your summit of this work!
But as it is noted that the project will open source at nearly 12 months before, when will you decide to provide the training and testing script?
Many thanks!

**Comment by whubaichuan** [comment]
@zhiwenfan please see my version [NPF-MVSNet](https://github.com/whubaichuan/NPF-MVSNet)

**Comment by tejaskhot** [comment]
Code uploaded now. Re-open if there are any issues.

**Comment by whubaichuan** [comment]
@zhiwenfan New codebase [M3VSNet](https://github.com/whubaichuan/M3VSNet)
